spring:
  datasource:
    url: jdbc:mysql://47.102.194.232:3306/help2?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: help2
    password: 123456
server :
  port : 8081
person:
  id: 1
  name: 花花
  age: 2
